[project]
name = "hydrodb"
version = "1.0.3"
authors = [
  { name="Caio Teixeira de Paula", email="caio.teixeira.paula@gmail.com" },
]
description = "A simple database package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU GENERAL PUBLIC LICENSE",
    "Operating System :: OS Independent",
    "Development Status :: 3"
]

[project.urls]
Homepage = "https://caioteixeiradepaula.github.io/Hydro/HydroDB/about_hydrodb"
